model_config:
  latent_dim: 1024
  num_layers: 12
  num_heads: 8
  num_kv_heads: null
  dim_feedforward: 4096
  num_register_tokens: 32
  register_token_pe: weighted_mean
  use_view_token: false
  dropout: 0.0
  activation: swiglu
  norm_type: rms_norm
  norm_first: true
  view_indep_qk_norm: true
  qk_norm: true
  bias: false
  pe_type: rope
  rope_type: triangle
  rope_double_max_freq: true
  vertex_pe_num_freqs: 12
  intra_rope_pe_num_freqs: 20
  use_vn_encoder: true
  vn_pe_num_freqs: 6
  vn_encoder_norm_type: rms_norm
  texture_encode_patch_size: 1
  texture_channels: 13
  texture_encoder_norm_type: rms_norm
  log_roughness_encoding: false
  separate_light_strength: false
  auto_interpolate_texture: false
  use_env_lighting: false
  envmap_vae_model_id: Qwen/Qwen-Image
  envmap_latent_patch_size: 8
  envmap_latent_channels: 16
  envmap_ray_dir_map_patch_size: 64
  envmap_encoder_norm_type: layer_norm
  use_triangle_ordering: false
  triangle_ordering_order: z
  view_transformer_use_triangle_ordering: false
  view_transformer_triangle_ordering_order: z
  use_local_attention: false
  local_attention_window_size_half: 256
  use_flex_attention: false
  flex_attention_block_size: 128
  put_light_tokens_first: false
  put_light_tokens_in_sink: true
  put_env_tokens_in_sink: true
  add_summary_tokens: false
  summary_block_size: 64
  use_volumes: false
  volume_density_input_dim: 64
  volume_use_density_mlp: true
  use_perceiver: false
  num_perceiver_tokens: 64
  decoding_method: view_transformer
  texture_decode_patch_size: 32
  view_transformer_latent_dim: 1024
  view_transformer_ffn_hidden_dim: 4096
  view_transformer_n_heads: 8
  view_transformer_num_kv_heads: null
  view_transformer_n_layers: 12
  view_transformer_include_self_attn: true
  view_transformer_self_attn_before_cross: false
  view_transformer_use_swin_attn: true
  vdir_pe_type: nerf
  vdir_num_freqs: 0
  patch_size: 8
  output_patch_size: null
  output_channel: null
  latent_vae_model_id: null
  include_alpha: false
  freeze_radiosity_transformer_if_initialized: false
  use_dpt_decoder: true
  dpt_features: 256
  dpt_out_channels:
  - 256
  - 512
  - 1024
  - 1024
  dpt_out_layers:
  - 2
  - 5
  - 8
  - 11
  view_transformer_use_layers: null
  custom_init: true
  deepstack_injection_map: null
  deepstack_dual_input_size: 64
  deepstack_decoder_injection_map: null
